[workspace]
members = ["owl-detection", "owl-vision", "owl-hardware", "python-bindings"]
resolver = "2"

[workspace.dependencies]
opencv = "0.92"
image = "0.25"
ndarray = "0.15"
rayon = "1.8"
numpy = "0.21"
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
