name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-14 llvm-14-dev libclang-14-dev
      - name: Install maturin
        run: pip install maturin
      - name: Build wheels
        run: maturin build --release --out dist
      - name: Run tests
        run: |
          cargo test --workspace
          pip install dist/*.whl
          pytest tests -vv
